// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type AbilityEffect = { "type": "damage", formula: string, damageType: DamageType, } | { "type": "heal", formula: string, } | { "type": "applyStatus", statusId: string, duration: string, savingThrow: SavingThrow | null, } | { "type": "modifyStat", attribute: Attribute, value: StatValue, durationRounds: number, } | { "type": "summon", entityId: string, quantity: string, } | { "type": "transform", targetEntityId: string, duration: string, revertOnDeath: boolean, } | { "type": "move", distance: number, direction: string, } | { "type": "areaOfEffect", shape: AoeShape, range: number, effects: Array<AbilityEffect>, } | { "type": "custom", description: string, data: Record<string, unknown>, };

export type AbilityExport = { id: string, name: string, slug: string, description: string, type: AbilityType, target: AbilityTarget | null, castingTime: string | null, requiresConcentration: boolean, components: SpellComponents | null, recharge: string | null, effects: Array<AbilityEffect>, createdAt: string, updatedAt: string, };

export type AbilityTarget = { "type": "selfTarget" } | { "type": "target", range: number, count: number, } | { "type": "area", shape: AoeShape, range: number, };

export type AbilityType = "action" | "bonusAction" | "reaction" | "passive" | "legendary" | "lair" | "mythic";

export type AoeShape = "sphere" | "cube" | "cone" | "line" | "cylinder";

export type AppError = { "type": "database", "content": { message: string, } } | { "type": "notFound", "content": { id: string, entityType: string, } } | { "type": "validation", "content": { errors: Array<string>, } } | { "type": "slugConflict", "content": { slug: string, } } | { "type": "dependencyConflict", "content": { message: string, } } | { "type": "io", "content": { message: string, } } | { "type": "tauri", "content": { message: string, } };

export type Attribute = "strength" | "dexterity" | "constitution" | "intelligence" | "wisdom" | "charisma";

export type DamageResistance = { damageType: DamageType, level: ResistanceLevel, };

export type DamageType = "acid" | "bludgeoning" | "cold" | "fire" | "force" | "lightning" | "necrotic" | "piercing" | "poison" | "psychic" | "radiant" | "slashing" | "thunder";

export type Durability = { current: number, max: number, };

export type EntityExport = { id: string, name: string, slug: string, taxonomy: Taxonomy, size: EntitySize | null, threatLevel: ThreatLevel | null, alignment: string | null, challengeRating: number | null, experiencePoints: number | null, proficiencyBonus: number | null, legendaryActionsPerRound: number | null, savingThrows: { [key in Attribute]?: number }, skills: Record<string, number>, damageResistances: Array<DamageResistance>, statusImmunities: Array<string>, senses: Array<string>, languages: Array<string>, habitats: Array<string>, description: string, statBlock: StatBlock, notes: string, statusIds: Array<string>, abilityIds: Array<string>, inventory: Array<LootDrop>, images: Array<string>, createdAt: string, updatedAt: string, };

export type EntitySize = "tiny" | "small" | "medium" | "large" | "huge" | "gargantuan";

export type GameEnums = { itemTypes: Array<ItemType>, rarities: Array<Rarity>, abilityTypes: Array<AbilityType>, aoeShapes: Array<AoeShape>, damageTypes: Array<DamageType>, entitySizes: Array<EntitySize>, threatLevels: Array<ThreatLevel>, attributes: Array<Attribute>, resistanceLevels: Array<ResistanceLevel>, };

export type ImportResult = { entitiesImported: number, itemsImported: number, statusesImported: number, abilitiesImported: number, errors: Array<string>, };

export type ItemExport = { id: string, name: string, slug: string, type: ItemType, description: string, icon: string, weight: number | null, bulk: number | null, rarity: Rarity | null, properties: Record<string, unknown>, equipSlots: Array<string>, statModifiers: Record<string, StatValue>, durability: Durability | null, createdAt: string, updatedAt: string, };

export type ItemType = "weapon" | "armor" | "consumable" | "trinket" | "material" | "organic" | "tool";

export type LootDrop = { itemId: string, quantity: string, dropChance: number, };

export type Rarity = "common" | "uncommon" | "rare" | "veryRare" | "legendary" | "mythic" | "unique";

export type ResistanceLevel = "vulnerable" | "resistant" | "immune";

export type SavingThrow = { dc: number, attribute: Attribute, };

export type SpellComponents = { verbal: boolean, somatic: boolean, material: string | null, };

export type StackingBehavior = "no" | "refresh" | "stack";

export type StatBlock = { hp: number | null, armor: number | null, speed: number | null, strength: number | null, dexterity: number | null, constitution: number | null, intelligence: number | null, wisdom: number | null, charisma: number | null, custom: Record<string, number | string>, };

export type StatValue = { "type": "flat", value: number, } | { "type": "percentAdd", value: number, } | { "type": "percentMult", value: number, };

export type StatusEffectPayload = { movePenalty: StatValue | null, attackPenalty: StatValue | null, defenseBonus: StatValue | null, durationRounds: number | null, durationMinutes: number | null, stacks: StackingBehavior, tags: Array<string>, custom: Record<string, unknown>, };

export type StatusExport = { id: string, name: string, shortTag: string, icon: string, color: string | null, summary: string, description: string, payload: StatusEffectPayload, createdAt: string, updatedAt: string, };

export type Taxonomy = { genus: string | null, species: string | null, subspecies: string | null, };

export type ThreatLevel = "trivial" | "easy" | "medium" | "hard" | "deadly" | "legendary";
